### ISSUE TITLE
Absorb `fdm-monster.net` landing page into documentation page

### ISSUE THREAD

**Issue by davidzwa** [fdm-monster/fdm-monster-docs#210]
### Checklist

- [X] I agree to follow our [Code of Conduct](https://github.com/fdm-monster/fdm-monster/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have verified no [other issues](https://github.com/fdm-monster/fdm-monster-docs/issues) exist related to my request.

### Is Your Feature Request Related To A Problem? Please describe.

Currently the FDM Monster landing page is outdated. We should aim for integrating this page to become part of the documentation setup. It should still be a landing page (some react code will be involved), but at least it becomes one codebase and we dont self-host it.

### Describe The Solution. Why is it needed?

The current landing page is not updated enough. It also seems to not be ideal for branding of the project.

### Additional Context

What
* [x] (NEW) Sponshorship - we should ensure users can sponsor the project or the two main devs
* [x] Documentation link - we should ensure the users understand that they can go to the "documentation" from the landing page 
* [x] Discord - we should add this as a button with logo (leading away from the site)
* [X] ~~OctoPrint - a nice button with logo (leading away from the site)~~
* [X] ~~(NEW) Moonraker - a nice button with logo~~
* [x] Let's Print (Github repo) => better direct to Getting Started
* [x] My proo and of Ewoud ... remove . If we want testimonials then ask FOSS users.

![image](https://github.com/user-attachments/assets/4f8ae65a-5133-4580-81cb-a4dea569d52c)

**Comment by mkevenaar** [comment]
* Adding OctoPrint and Moonraker doesn't scale for plans.
